I will beatify the Readme.md File
euronay/deferat pull request #25
Opened 2022-10-08 08:17 UTC by BxtGeek

Thanks for reading my pull request

2022-10-10 19:54 UTC, euronay requested changes

2022-10-10 19:54 UTC, euronay commented on README.md
> +## 📘 Usage
You've got duplicate "Simply Run" and "Usage" lines, could you tidy these up, please?

2022-10-11 02:47 UTC, BxtGeek commented
Sure will do that

2022-10-11 02:52 UTC, BxtGeek commented
Added the PR with the proper changes please check

2025-08-21 14:44 UTC, closed without merging